/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Canvas: typeof import('./components/canvas.vue')['default']
    ComponentList: typeof import('./components/component-list.vue')['default']
    HeaderOperation: typeof import('./components/header-operation.vue')['default']
    MidCanvas: typeof import('./components/mid-canvas.vue')['default']
    RightProperty: typeof import('./components/right-property.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
